import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "@/components/SideNavBar";
import Header from "@/components/Header";
import { Providers } from "../../GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-white text-black">
        <Providers>
          <Header />
          <div className="flex min-h-screen w-full">

            <SideNavBar />
            <div className="w-full p-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html >
  );
}
